### ISSUE TITLE
Team 5 (Hakan & Melisa)

### ISSUE THREAD

**Issue by MelisaSarici** [odtu/ee463#1]
@ozank 

Hocam, 2. soruda farklı loadlar için ölçüm yapmamız istenmiş. Buradaki voltage ölçümünü yalnızca R dan mı yoksa seri bağlı RL in tamamından mı almamız isteniyor?

**Comment by hakanpolat** [comment]
@ozank 
Hocam ayrıca 2.4 te simulasyonda bir şey gözlemleyemiyoruz. Ancak load L sini arttırınca ideal current source gibi davrandığından commutation gözlemliyoruz. Verilen değerlerle değişiklik olmaması normal mi?
Teşekkürler

**Comment by ilkersahin78** [comment]
RL in tamamından,

ödevdeki bazı değerler güncellenecek, L ler biraz küçük gelmiş
