### ISSUE TITLE
Source Voltage

### ISSUE THREAD

**Issue by Mertkaracelebi** [odtu/ee463#11]
İyi akşamlar hocam,
Hardware projectde 3 faz çalışırken voltaj seviyesini ayarlayabiliyor muyuz ? Yoksa 400V (line to line) çalışmak zorunda mıyız ?

**Comment by ozank** [comment]
Girişe isteyen gruplar variac bağlayabilecek. Variac'ı soft start için, ya da giriş voltajını ayarlamak için kullanabilirsiniz. Ancak, motor çalışırken variacla oynama hakkınız yok.
