### ISSUE TITLE
Project 3 teams

### ISSUE THREAD

**Issue by hakanpolat** [odtu/ee463#14]
@ozank @ilkersahin78 
Hocam iyi akşamlar,
Geçen projedeki gibi takım oluşturma sayfasını bu projede göremedim. Acaba kendimiz repo açıp sizleri mi eklememiz gerekiyor ?
Saygılarımla
Hakan Polat

**Comment by yusufbyilmaz** [comment]
Bu projede gruplar direkt ekli geldi.

**Comment by yusufbyilmaz** [comment]
Yani takımlara repolar açılmış ve assign edilmişiz

**Comment by hakanpolat** [comment]
aa sağolasın yusuf görmemişim teşekkür ederim.
