### ISSUE TITLE
Universal bridge-thyristor

### ISSUE THREAD

**Issue by yusufbyilmaz** [odtu/ee463#15]
Merhaba, iyi akşamlar
Simulinkte, universal bridge kullanarak controllable rectifier yapamaya çalışırken bir problemle karşılaşıyorum ve çözemedim. Gate e sinyal verirken aşağıda vermişolduğum matrice i phase delay kısmına g,r,yorum ve beklediğim sonucu elde edemiyorum. Beklediğim sonuç firing angle'ı 30 derece olan 3-phase rectifier çıkışı. Teşekkürler, iyi akşamlar tekrardan.

[(30/360)*20e-3 (210/360)*20e-3 (-90/360)*20e-3 (90/360)*20e-3 (150/360)*20e-3 (330/360)*20e-3] 
Bu arada frekans olarak 50 Hz kullanmaktayım.

**Comment by ilkersahin78** [comment]
Çözüldüğü için mi kapattın?

**Comment by yusufbyilmaz** [comment]
evet hocam, sonradan hallettim olayı.
