### ISSUE TITLE
EE 463 Project 3 - Q3 - TABLE 2 ?

### ISSUE THREAD

**Issue by caneryagci** [odtu/ee463#16]
Merhaba Hocam,
Project 3 - Q3'te aşağıdaki gibi bir ibare var ama table 2'yi bulamadık. Bir check edebilir misiniz.
"Afterwards, go to the “Op Vals” button at the top panel and fill the Table 2 given below. "
@ozank @ilkersahin78 
Saygılarımla,
Bekir Caner Yağcı

**Comment by ilkersahin78** [comment]
İlgili paragrafın altındaki nesneler tablo halinde çıkmamış da bullet lar halinde çıkmış. Tablo halinde çıksaymış Table 2 olasıymış
