### ISSUE TITLE
Hardware project requirement

### ISSUE THREAD

**Issue by sadikakyar** [odtu/ee463#17]
Hocam output voltajının 180 Volttan yüksek olması gerektiği yazılmış project descriptionda. (Output: Adjustable DC Output (Vmax> 180 Vdc))
Bu voltaj değeri çok keskin bir şekilde bakılacak mı? Çünkü  input olarak 400 volt ve bir tane thyristor kullandığımız vakit average voltage 180 volt çıkıyor. Thyristor üzerinde de voltage drop olacak. Sonuçta output 180 volttan biraz daha az çıkacak. Bu kabul edilir mi?

**Comment by ozank** [comment]
Kabul ederim. 400x0.45=180V dan hesaplamıştım limiti.
