### ISSUE TITLE
Project Repoları

### ISSUE THREAD

**Issue by ozank** [odtu/ee463#18]
Arkadaşlar,
Projeleriniz için açtığınız repo adreslerini bugün bana bildirir misiniz? Donanımda çok ilerlemeden tasarımlarınız hakkında yorumda bulunmak istiyorum.
Aşağıdaki bilgiler lazım:

- Ekip Adı:
- Ekip Üyeleri:
- Public Repo Adresi:

**Comment by hhintoglu** [comment]
SPARK Industries
Huzeyfe Hintoglu, Sadık Akyar, Muhammed Hakan Karakaya
https://github.com/hhintoglu/EE463_Hardware_Project

**Comment by sametyildirima** [comment]
FosFos AG
Samet Yıldırım, Ozan Can İyier, Furkan Karacabey
https://github.com/sametyildirima/FosFos-AG

**Comment by ismail-ataseven** [comment]
BiB Power
İsmail Ataseven, Berkay Sağlam, Batuhan Bülbül
https://github.com/ismail-ataseven/BiB-Power

**Comment by nailtosun** [comment]
Firing Angels
Nail Tosun
Ali Aydın 
Özgür Ertürk
https://github.com/nailtosun/EE-463-Hardware-Project

**Comment by tokgozfurkan** [comment]
The Third Harmonics
Furkan Tokgöz
Enes Ayaz
Yasin Durmaz
https://github.com/EnesAyaz/EE463-HardwareProject

**Comment by bulbulbahar** [comment]
The Mega Hurts
Bahar Bülbül
Etki Açılan
Hakkı Gülcü
https://github.com/bulbulbahar/EE463_HardwareProject

**Comment by gurkandyilmaz** [comment]
K.A.R.P.U.Z.
Ali Aydın Yamandağ
Gürkan Durmuş Yılmaz
Sonay Ulukaya
https://github.com/gurkandyilmaz/EE463-Hardware_Project

**Comment by gurkan-yilmaz-kariyer-arge** [comment]
K.A.R.P.U.Z.
Ali Aydın Yamandağ
Gürkan Durmuş Yılmaz
Sonay Ulukaya
https://github.com/gurkandyilmaz/EE463-Hardware_Project

**Comment by anilcanbudak** [comment]
Freewheeling Co.
Anılcan Budak
Cem Akıncı
Murat Çolakoğlu
https://github.com/anilcanbudak/EE463-Hardware-Project

**Comment by nazliogluahmet** [comment]
A.N.
Ahmet Nazlıoğlu
https://github.com/nazliogluahmet/EE_463_proje_AN

**Comment by onurmetueee** [comment]
Smart Grid
Saliha İven Güzel
Ekin Su Saçın
Onur Külahlıoğlu
https://github.com/ivenguzel/EE463-Harware_Project

**Comment by mertelmas** [comment]
METU LELS
Mehmet Elen
Mert Elmas
Yusuf Selim Karataş
https://github.com/yusufselimkaratas/463HardwareProject

**Comment by nevzatsafasenyayla** [comment]
M.A.N.Power

Nevzat S. Şenyayla
Akın Şavklı
Metehan Kara

https://github.com/nevzatsafasenyayla/M.A.N.Power
