### ISSUE TITLE
Solver Selection Changes the Results EE463-Simulation Project 1

### ISSUE THREAD

**Issue by edsenel** [odtu/ee463#19]
In the simulations, the solver selection changes the results according to my simulations. Do we have to use any solver method or is it up to us? Because the results and values will be different from each other depending on the solver selection!

**Comment by ghandeb** [comment]
ben şimdiye kadar hep auto (otomatik seçen) solver'ı kullandım.
bir de solver step size için variable step değil fixed step kullanman daha iyi olur. variable step olduğu durumda bazen step size gereksiz yere küçülüyor singularity hatası falan alabiliyorsun, veya steady state durumunda step size olması gerekenden büyük olduğu için accuracy sorunu yaşıyorsun. bu yüzden 1e-6 (5 veya 7 de olabilir, simülasyon süresine ve switching frekansına bağlı) gibi bir fixed step size sana istediğin accuracy'de bir sonuç verecektir

**Comment by edsenel** [comment]
teşekkür ederim. auto solver seçip time stepi düşürünce sorun düzeldi
