### ISSUE TITLE
team

### ISSUE THREAD

**Issue by ekinalpb** [odtu/ee463#2]
hocam ben kendi 13. grubuma dahil olmaya çalıştığımda "You are forbidden from performing this action on github.com" diye bir hata veriyor. bunu nasıl çözebiliriz

**Comment by ozank** [comment]
Selam sana manual olarak admin yetkisi verip, ekledim. Bir daha denesene.
Bir de 13. takıma ait 2 tane repo gorunuyor, hangisinde çalışıyorsunuz?

https://github.com/odtu/ee463-project1-team-13
https://github.com/odtu/ee463-project1-team-13-1

**Comment by ekinalpb** [comment]
merhaba hocam,

Geçen gün siz odtü grubuna ekledikten sonra girebildim sanırsam 13. gruba.
Neden 2 tane repo olduğunu da anlamadım ama bizimki 13-1.

2017-11-09 10:25 GMT+03:00 Ozan K <notifications@github.com>:
