### ISSUE TITLE
Diode current change ratio

### ISSUE THREAD

**Issue by MERTAYDIN46** [odtu/ee463#20]
Merhaba,
Diyotun dif/dt oranı yani forward akımının değişim oranı diyotun bulunduğu devredeki diğer elemanlara mı bağlı? Çünkü diyotun kendi inductance’ı çok düşük bir sevide gözüküyor data sheet lerde ?

**Comment by gkhnckl** [comment]
Akım yolu üzerindeki tüm elemanların endüktansı devre dinamiği etkileyecektir.
