### ISSUE TITLE
Dc motor parameters

### ISSUE THREAD

**Issue by MERTAYDIN46** [odtu/ee463#23]
Merhaba hocam,
Rated speed de motorun ne kadar akım çekeceğini bulmamız için shaftın üzerindeki torque u bilmemiz gerekiyor ideal olarak 0 bu yüzden simulasyonda göremiyoruz. Eğer bunu bulamasak bile back emf constant lazım bunları acaba bizimle paylaşırmısınız bide inertiayı 1 olarak aldık ama sorun olmaz değil mi hocam? Son olarak sanırım power hesabı için kattle ın direnci verilmişti ama aklımızdan çıkmış o kaçtı acaba?

**Comment by gkhnckl** [comment]
Selam,

Kettle'ın rated power ve rated speed'i burada [burada](https://github.com/odtu/ee463/tree/master/Hardware-Project) yazıyor. Verimi de 0.9 varsayıp kabaca tork hesaplayabilirsin. Inertia ise benzer boyutlardaki bir motoru inceleyip aynı değeri alabilirsin. Kettle direncini de rated power'dan bulabilirsin.
