### ISSUE TITLE
Project4

### ISSUE THREAD

**Issue by MERTAYDIN46** [odtu/ee463#24]
Merhaba,
4.projenin 1.nci sorusunun c şıkkında boundary current için bazı waveformlar isteniyor daha sonra d şıkkında da aynısını yapmamız isteniyor fakat ben tam olarak d şıkkında ne isteniyor anlamadım çünkü output voltajı 3.3V olacaksa verilen rated power için Boundary condıction mode olmuyor veya boundary current dan yola çıkarsak output voltage 3.3V olmuyor hangisi isteniyor tam olarak acaba?

**Comment by gkhnckl** [comment]
Selam,

d şıkkında BCM olmak zorunda değil. Hangi modda çalışıyorsa ona göre sonuçları almanız gerekiyor.
