### ISSUE TITLE
Thyristor firing angle arrangment

### ISSUE THREAD

**Issue by alpercak** [odtu/ee463#27]
Hello friends,

Can anyone help me to guide how to give firing angle to the thyristors? I am trying to give gate signals with pulse generator like 0.02s with enough voltage to activate thyristor. So far I couldnt get appropirate result. Thanks

**Comment by tokgozfurkan** [comment]
Hi,
You can have a look at the following link: https://www.mathworks.com/help/physmod/sps/powersys/ref/pulsegeneratorthyristor.html

**Comment by alpercak** [comment]
Thank you, it helps a lot!
