### ISSUE TITLE
?

### ISSUE THREAD

**Issue by MelisaSarici** [odtu/ee463#4]
@ozank 
Hakan'ın rapora yazdığı bir commenti okurken düzeltmek ve sormak istediğim bir nokta doğdu hocam, power hesabını yaparken Voltajın total rms'ini currentin fundamental rmsi ile çarpıp integral ediyoruz ve kitapta da bu şekilde yazıyor, yani aktif power akımın fundamental componentindan gelmekte. Siz de derste bu şekilde söylediniz diye hatırlıyorum. Ancak bunun sebebi nedir kitapta yazmıyor. Bu nokta aklıma takıldı.

**Comment by ilkersahin78** [comment]
Güzel soru, atlıyorum:

Mohadan ziyade aktif ve reaktif power ın tanımları için circuit kitabını tavsiye ederim, nilsson.

Sebep: Mesela yalnızca birinci ve üçüncü harmoniklerin olduğu bir sistemde: integral(sin(x).sin(3x).dx)=0 (limitler:  0 dan pi ye).

Dolayısıyla güç harmonkten değil fundamentalden geliyor

**Comment by MelisaSarici** [comment]
Teşekkür ederim hocam, şimdi anladım. Dediğiniz üzere işlemleri yapınca da çıkıyor. 👍

**Comment by ozank** [comment]
ilker'e :clap: :clap:
