### ISSUE TITLE
Project 2 Team selection

### ISSUE THREAD

**Issue by hakanpolat** [odtu/ee463#6]
@ozank 
Hocam merhabalar,
Yolladığınız linke ( https://classroom.github.com/g/JGd7lc_7 )tıklayınca you are forbidden hatası alıyorum. Ne yapmalıyım? Takımım 7.

**Comment by ozank** [comment]
Herkeste aynı sorun olmuş, ben bi hata yaptım galiba.
Kontrol edip linki tekrar yollayacağım
