### ISSUE TITLE
İlk soru

### ISSUE THREAD

**Issue by MelisaSarici** [odtu/ee463#7]
@ozank 

Hocam ilk soruda, average current verilmiş. 

$V_{av }=2*sqrt(2)/pi*V_{s}*cos(\alpha) - 2*L_{s}*I_{d}*\omega/pi $
 denkleminde `I_{d}=40` koyarak alphayı çekmeyi düşündüm ancak average voltage gerekli mi yoksa ben yanlış yoldan mı düşünüyorum?

**Comment by ilkersahin78** [comment]
a şıkkı için doğru

**Comment by MelisaSarici** [comment]
@ilkersahin78 
Hocam average voltaj nedir o zaman istenen? L-R devresinden bir Z çekip Z*Iav ile bizim mi bulmamız lazım? Öyleyse eğer ben çok saçma bir değer buluyorum da 😀

**Comment by ilkersahin78** [comment]
L nin averaj voltajı sıfır değil mi?

**Comment by MelisaSarici** [comment]
@ilkersahin78 Evet hocam çok haklısınız, teşekkür ettim. 👍

**Comment by ilkersahin78** [comment]
Rica ederim

**Comment by ozank** [comment]
:+1: başkalarının da işine yararsa diye tekrar etkinleştiriyorum bunu
